const data = {
  products: [
    {
      name: "Nike-slim-shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Addidas-fit-shirt",
      slug: "addidas-fit-shirt",
      category: "Shirts",
      image: "images/p2.jpg",
      price: 220,
      countInStock: 10,
      brand: "Addidas",
      rating: 6,
      numReviews: 15,
      description: "high quality shirt",
    },
    {
      name: "Nike-slim-pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pant",
    },
    {
      name: "Addidas-slim-pant",
      slug: "addidas-slim-pant",
      category: "Pants",
      image: "images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pant",
    },
  ],
};
export default data;
